spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: r1
            uri:
              http://localhost:8085/
            predicates:
              - Path=/rest1/**
          - id: r2
            uri:
              http://localhost:8086/
            predicates:
              - Path=/api2/**
server:
  port: 8888